# activation function

# sigmoid (0~1之間)


\begin{equation}
\sigma(x) =\frac{1}{1+e^{-x}}  
\end{equation}

In [2]:
import torch
a=torch.linspace(-100,100,10)
print(torch.sigmoid(a))

tensor([0.0000e+00, 1.6655e-34, 7.4564e-25, 3.3382e-15, 1.4945e-05, 9.9999e-01,
        1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00])


# Tanh (-1~1之間)

\begin{equation}
Tanh(x) =\frac{e^x-e^{-x}}{e^x+e^{-x}}  
\end{equation}

In [3]:
b=torch.linspace(-1,1,10)
print(torch.tanh(b))

tensor([-0.7616, -0.6514, -0.5047, -0.3215, -0.1107,  0.1107,  0.3215,  0.5047,
         0.6514,  0.7616])


# ReLU

$$ f(n)= \begin{cases} 0, & \text {if $n$ <0} \\ n, & \text{if $n$ $\geq$ 0} \end{cases} $$

In [4]:
c=torch.linspace(-1,1,10)
print(torch.relu_(c))

tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.1111, 0.3333, 0.5556, 0.7778,
        1.0000])


# Softmax (0~1之間)

\begin{equation}
 f(x_j)= \frac{e^{x_i}} {\sum_{i=0}^n{e^{x_i}}}
\end{equation}

In [6]:
from torch.nn import functional as F
y=torch.rand(3,requires_grad=True)
print(y)
p=F.softmax(y,dim=0)
print(p)

tensor([0.6990, 0.3012, 0.8941], requires_grad=True)
tensor([0.3464, 0.2327, 0.4210], grad_fn=<SoftmaxBackward>)


In [12]:
from math import exp
exp(0.3012)/(exp(0.6990)+exp(0.3012)+exp(0.8941))

0.23267859855548678

# Loss function

# MSE ( Mean Squared Error)

\begin{equation}
 MSE=  \sum_{i=0}^n {(y_i-(wx_i+b))^2}
\end{equation}

In [18]:
y=0.2 
pred = torch.randn(10)
mse=(pred-y).norm(2).pow(2)
print(mse)
pred

tensor(7.9566)


tensor([-2.4879,  0.0075,  0.4899,  0.0115, -0.2638,  0.0579, -0.1706,  0.1368,
        -0.2345,  0.2991])

In [21]:
for i in range(100):
    print("抽",end='')

抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽抽