# tensor的合併cat(要合併的其他dim size要一樣)

In [71]:
import torch  
a=torch.rand(4,32,8)
b=torch.rand(4,32,7)
print(torch.cat([a,b],dim=2).shape) #8+7

torch.Size([4, 32, 15])


# 合併新增(stack)

In [72]:
x1=torch.rand(4,3,32,32)
x2=torch.rand(4,3,32,32)
x3=torch.rand(4,3,32,32)
print(torch.stack([x1,x2],dim=1).shape) #2張
print(torch.stack([x1,x2,x3],dim=1).shape) #3張

torch.Size([4, 2, 3, 32, 32])
torch.Size([4, 3, 3, 32, 32])


# tensor的拆開(split)

In [73]:
#固定1張
a=torch.rand(2,4,3,32,32)
a1,a2=a.split(1,dim=0) #把兩張紙撕成一張一張 hint只能撕成1張不能16 16分
print(a1.shape,a2.shape) 
#分割成自己要的
b=torch.rand(4,3,32,32)
b1,b2=b.split([1,2],dim=1) #b1配1 b2配2
print(b1.shape,b2.shape) 

torch.Size([1, 4, 3, 32, 32]) torch.Size([1, 4, 3, 32, 32])
torch.Size([4, 1, 32, 32]) torch.Size([4, 2, 32, 32])


# 等分分割(chunk)

In [74]:
c=torch.rand(7,4)
c1,c2,c3,c4=c.chunk(4,dim=0) #將dim=0 size拆成4分
print(c1.shape,c2.shape,c3.shape,c4.shape)

torch.Size([2, 4]) torch.Size([2, 4]) torch.Size([2, 4]) torch.Size([1, 4])


# Broadcasting

1、Broadcasting(廣播)也就是自動實現了unsqueeze expand

2、Broadcasting能夠實現自動維度擴展，有點像上節學的expandrepeat

比如得到的feature maps的維度是[4,32,14,14]，對這些特徵圖加上偏置，bias[32],先對bias進行unsqueeze操作增加維度：[1,32,1,1]，再用expand操作進行擴充[4,32,14,14]。然後兩者就可以相加了。

這種情況是可以使用Broadcasting的，可以避免自己手動的寫多個操作，以更高效的方式計算。

# 相加

In [75]:
a=torch.rand(4,32,14,14)
b=torch.rand(1,32,1,1)
c1=a+b
c2=torch.add(a,b)
print(c1.shape,c2.shape)
# if all elements are same return True
# torch.eq(torch.tensor([[1, 2], [3, 4]]), torch.tensor([[1, 1], [4, 4]]))
# tensor([[ True, False],   [False, True]])
print(torch.all(torch.eq(c1,c2)))
a=torch.ones(3,4)
torch.all(a)

torch.Size([4, 32, 14, 14]) torch.Size([4, 32, 14, 14])
tensor(True)


tensor(True)

# 相減

In [76]:
a=torch.rand(4,32,14,14)
b=torch.rand(1,32,1,1)
c1=a-b
c2=torch.sub(a,b)
print(c1.shape,c2.shape)

torch.Size([4, 32, 14, 14]) torch.Size([4, 32, 14, 14])


In [77]:
#查看相加的element結果
a=torch.rand(3,4)
b=torch.rand(4)
c1=a+b
c2=torch.add(a,b)
print(c1.shape,c2.shape)
a,b,c1

torch.Size([3, 4]) torch.Size([3, 4])


(tensor([[0.6639, 0.5441, 0.0303, 0.3572],
         [0.3065, 0.0443, 0.6757, 0.0376],
         [0.9925, 0.8463, 0.6836, 0.4308]]),
 tensor([0.9233, 0.4465, 0.4740, 0.0923]),
 tensor([[1.5872, 0.9906, 0.5044, 0.4495],
         [1.2297, 0.4908, 1.1497, 0.1298],
         [1.9158, 1.2928, 1.1576, 0.5230]]))

# 哈達瑪積(element wise)乘法

跟一般矩陣乘法不同
$$
\begin{Bmatrix}
 a_1&a_2&a_3\\
 a_4&a_5&a_6\\
 \end{Bmatrix} 
 *
 \begin{Bmatrix}
 b_1&b_2&b_3\\
 b_4&b_5&b_6\\
 \end{Bmatrix} 
 =
 \begin{Bmatrix}
 a_1b_1&a_2b_2&a_3b_3\\
 a_4b_4&a_5b_5&a_6b_6\\
 \end{Bmatrix} 
$$


In [78]:
a=torch.rand(1,2)
b=torch.rand(2)
c1=a*b
c2=torch.mul(a,b)
c3=a/b
c4=torch.div(a,b)
print(c1.shape,c2.shape)
a,b,c1,c4

torch.Size([1, 2]) torch.Size([1, 2])


(tensor([[0.9161, 0.0338]]),
 tensor([0.7299, 0.0733]),
 tensor([[0.6686, 0.0025]]),
 tensor([[1.2552, 0.4614]]))

# 矩陣乘法

$$
\begin{Bmatrix}
 a_1&a_2\\
 a_3&a_4\\
 \end{Bmatrix} 
 *
 \begin{Bmatrix}
 b_1\\
 b_2\\
 \end{Bmatrix} 
 =
 \begin{Bmatrix}
 a_1b_1+a_2b_2\\
 a_3b_1+a_4b_2\\
 \end{Bmatrix} 
$$


In [79]:
a=torch.ones(2,1)
b=torch.ones(1,2)
print(torch.mm(a,b).shape)
print(torch.matmul(a,b).shape)
print((a@b).shape)

torch.Size([2, 2])
torch.Size([2, 2])
torch.Size([2, 2])


dim>2
對於高維的Tensor，定義其矩陣乘法僅在最後的兩個維度上，要求前面的維度必須保持一致，就像矩陣的索引一樣。


In [80]:
c = torch.rand(4, 3, 28, 64)
d = torch.rand(4, 3, 64, 32)
print(torch.matmul(c, d).shape)

torch.Size([4, 3, 28, 32])


注意，在這種情形下的矩陣相乘，前面的"矩陣索引維度"如果符合Broadcasting機制，也會自動做廣播，然後相乘

In [81]:
c1=torch.rand(4,3,28,64)
c2=torch.rand(4,1,64,32)
print((c1@c2).shape)

torch.Size([4, 3, 28, 32])


In [82]:
a=torch.full([2,2],3)
b=a.pow(2) 
print(b)
b=b.sqrt()#也可以寫b**0.5
print(b)
b=b.rsqrt() #開跟號分之一
print(b)

tensor([[9, 9],
        [9, 9]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[0.5774, 0.5774],
        [0.5774, 0.5774]])


# 指數與對數

In [83]:
a=torch.exp(torch.ones(2,2))
print(a)
print(torch.log(a)) #nature log ->ln
print(torch.log2(a))


tensor([[2.7183, 2.7183],
        [2.7183, 2.7183]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[1.4427, 1.4427],
        [1.4427, 1.4427]])


# 近似值操作

In [84]:
a=torch.tensor(3.14)
print(a.floor(),a.ceil(),a.trunc(),a.frac()) #取下，取上，取整數，取小數
c=torch.tensor(4.51)
print(c.round()) #hint .5不會四捨五入

tensor(3.) tensor(4.) tensor(3.) tensor(0.1400)
tensor(5.)


# 裁剪

即對Tensor中的元素進行範圍過濾，不符合條件的可以把它變換到範圍內部（邊界）上，常用於梯度裁剪（gradient clipping），即在發生梯度離散或者梯度爆炸時對梯度的處理。

In [85]:
grad = torch.rand(2,3)*15 #0~15隨機生成
print(grad.max(),grad.min(),grad.median()) #最大、最小、中位數
print(grad)
print(grad.clamp(10))#小於10都拉成10
print(grad.clamp(3,10)) #小於3變成3 大於10變成10

tensor(13.3450) tensor(2.6305) tensor(5.2362)
tensor([[ 5.2362, 13.3450,  8.0211],
        [ 4.8081,  2.6305,  7.4908]])
tensor([[10.0000, 13.3450, 10.0000],
        [10.0000, 10.0000, 10.0000]])
tensor([[ 5.2362, 10.0000,  8.0211],
        [ 4.8081,  3.0000,  7.4908]])
