In [2]:
import torch
import numpy as np 

In [10]:
y_numpy = np.array([3,4,5.])
print(np.linalg.norm(y_numpy)), (3**2+4**2+5**2)**(1/2)

7.0710678118654755


(None, 7.0710678118654755)

In [12]:
a = torch.rand(1, 2, 3)
a[0]

tensor([[0.3828, 0.7397, 0.4490],
        [0.7788, 0.4316, 0.4386]])

In [3]:
a = torch.randn(2, 3)
print(a.type())
print(isinstance(a, torch.cuda.FloatTensor))
a = a.cuda()  # 转换为GPU上的类型
print(a.type())
print(isinstance(a, torch.cuda.FloatTensor))

torch.FloatTensor
False


AssertionError: Torch not compiled with CUDA enabled

# 從numpy建立

In [1]:
import torch
import numpy as np

a = np.array([2, 3.3])
a = torch.from_numpy(a)  # torch.DoubleTensor

# list建立

In [2]:
a = torch.FloatTensor([2, 3.3])  # 尽量少用这种方式,容易和给shape的情况看混淆
b = torch.tensor([2, 3.3])  # 现有list时尽量用这种方式

# 宣告空間

In [3]:
a = torch.empty(2, 3)
b = torch.FloatTensor(2, 3)
c = torch.IntTensor(2, 3)
a,b,c

(tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[0, 0, 0],
         [0, 0, 0]], dtype=torch.int32))

# 修改tensor的默認類型

In [9]:
print(torch.tensor([1, 2.2]).type())
torch.set_default_tensor_type(torch.FloatTensor)
print(torch.tensor([1, 2.2]).type())

torch.DoubleTensor
torch.FloatTensor


In [5]:
print(torch.tensor([1, 2.2]).type())

torch.DoubleTensor


# assign value

In [36]:
#採樣自0~1均勻分佈
a = torch.rand(3, 3)

# 形如*_like接受一個Tensor,將這個Tensor的shape讀取出來之後在送入*所表示的函數
# 下面的rand_like(a)即將a的shape=3,3讀出來傳給torch.rand()函數
b = torch.rand_like(a)  # 相當於執行了torch.rand(3,3)

# 在區間[1,10)上隨機採樣,生成shape=2,2的LongTensor
c = torch.randint(1, 10, [2, 2])

# 採樣自N(0,1)
d = torch.randn(3, 3)
# shape=2,3,所使用的相同的元素为7
e = torch.full([2, 3], 7)
# 指定均值和標準差
f = torch.normal(mean=torch.full([10], 0.0), std=torch.arange(1, 0, -0.1)) #注意要0.0(float)
#對角矩陣
g = torch.eye(4, 4)
#1矩陣
h=torch.ones(3,4)
#指數成長
i=torch.logspace(start=1, end=10, steps=10, base=2) #從base的start次方取到end次方 並且間隔step個
'a.採樣自0~1均勻分佈',a,'b.like()',b,'c,在區間[1,10)上隨機採樣 shape(2,2)',c, 'd.採樣自N(0,1)',d \
,'e.shape=2,3,所使用的相同的元素为7',e,'f.指定均值和標準差',f,'g.對角矩陣',g,'h.1矩陣',h,'i.指數成長',i

('a.採樣自0~1均勻分佈',
 tensor([[0.5508, 0.4220, 0.5236],
         [0.8468, 0.0456, 0.3533],
         [0.3662, 0.8126, 0.5907]]),
 'b.like()',
 tensor([[0.6644, 0.0191, 0.1272],
         [0.6289, 0.0827, 0.0267],
         [0.8673, 0.3076, 0.4980]]),
 'c,在區間[1,10)上隨機採樣 shape(2,2)',
 tensor([[8, 3],
         [1, 5]]),
 'd.採樣自N(0,1)',
 tensor([[ 0.3809, -0.9997,  1.2656],
         [ 1.7071,  0.0792,  2.5680],
         [ 0.2738,  0.4879,  0.7644]]),
 'e.shape=2,3,所使用的相同的元素为7',
 tensor([[7, 7, 7],
         [7, 7, 7]]),
 'f.指定均值和標準差',
 tensor([ 0.2221,  1.0829, -0.3748,  0.3175, -0.2827, -0.5334, -0.3494, -0.2591,
          0.0600,  0.0923]),
 'g.對角矩陣',
 tensor([[1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 1., 0.],
         [0., 0., 0., 1.]]),
 'h.1矩陣',
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 'i.指數成長',
 tensor([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512., 1024.]))

In [21]:
torch.logspace(start=1, end=10, steps=10, base=2)

tensor([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512., 1024.])