In [1]:
import torch

a = torch.rand(4, 3, 28, 28)
print(a[0].shape)
print(a[0, 0].shape)
print(a[0, 0, 0, 0])  # 到某個index的元素
# a

torch.Size([3, 28, 28])
torch.Size([28, 28])
tensor(0.3146)


# 切片

In [2]:
print(a[:2].shape)  # 在第一個維度上取後0和1
print(a[:2, :1, :, :].shape)  # 在第一個維度上取0和1,在第二個維度上取0
print(a[:2, 1:, :, :].shape)  # 在第一個維度上取0和1,在第二個維度上取1,2
print(a[:2, -2:, :, :].shape)  # 在第一個維度上取0和1,在第二個維度上取1,2

torch.Size([2, 3, 28, 28])
torch.Size([2, 1, 28, 28])
torch.Size([2, 2, 28, 28])
torch.Size([2, 2, 28, 28])


In [3]:
print(a[:, :, 0:28:2, 0:28:2].shape)  # step=2隔行採樣
print(a[:, :, ::2, ::2].shape)  # 等同於這個

torch.Size([4, 3, 14, 14])
torch.Size([4, 3, 14, 14])


In [4]:
# 選維度跟範圍
# 選擇第一張和第三張圖
print(a.index_select(0, torch.tensor([0, 2])).shape)
# 選擇R通道和B通道
print(a.index_select(1, torch.tensor([0, 2])).shape)

torch.Size([2, 3, 28, 28])
torch.Size([4, 2, 28, 28])


# 多個維度

In [5]:
print(a[:, 1, ...].shape)
print(a[..., :2].shape)
print(a[0, ..., ::2].shape)

torch.Size([4, 28, 28])
torch.Size([4, 3, 28, 2])
torch.Size([3, 28, 14])


# mask索引 (篩選類似if)

In [6]:
# 取出a這個Tensor中大於0.5的元素
a = torch.randn(3, 4)
print(a)
x = a.ge(0.5)
print(x)
print(a[x])
# torch.ge?

tensor([[ 0.1478, -0.2105,  0.3812,  0.9232],
        [-0.4482,  1.4813, -0.8363, -1.0991],
        [ 0.2347, -0.6172, -0.3615,  0.6498]])
tensor([[False, False, False,  True],
        [False,  True, False, False],
        [False, False, False,  True]])
tensor([0.9232, 1.4813, 0.6498])


# task索引 (創建new tensor並可指定index)

In [7]:
a = torch.tensor([[3, 7, 2], [2, 8, 3]])
print(a)
print(torch.take(a, torch.tensor([0, 1, 5]))) #index:0、1、5

tensor([[3, 7, 2],
        [2, 8, 3]])
tensor([3, 7, 3])
